#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>
#include <stdint.h>

static const wchar_t *kPath=L"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Command & Conquer Red Alert II\\game.exe";
static DWORD find_target(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(s==INVALID_HANDLE_VALUE)return 0;PROCESSENTRY32W e={0};e.dwSize=sizeof(e);DWORD r=0;if(Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);if(p){wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(QueryFullProcessImageNameW(p,0,q,&n)&&!_wcsicmp(q,kPath))r=e.th32ProcessID;CloseHandle(p);}}}while(!r&&Process32NextW(s,&e));CloseHandle(s);return r;}
int wmain(int argc,wchar_t **argv){if(argc!=2)return 2;uintptr_t target=(uintptr_t)wcstoul(argv[1],0,16);DWORD pid=find_target();if(!pid)return 3;HANDLE p=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ,FALSE,pid);if(!p)return 4;SYSTEM_INFO si;GetSystemInfo(&si);unsigned char *a=(unsigned char*)si.lpMinimumApplicationAddress,*m=(unsigned char*)si.lpMaximumApplicationAddress;MEMORY_BASIC_INFORMATION x;unsigned n=0;while(a<m&&VirtualQueryEx(p,a,&x,sizeof(x))==sizeof(x)){DWORD pr=x.Protect&0xff;BOOL rd=pr==PAGE_READONLY||pr==PAGE_READWRITE||pr==PAGE_WRITECOPY||pr==PAGE_EXECUTE_READ||pr==PAGE_EXECUTE_READWRITE||pr==PAGE_EXECUTE_WRITECOPY;if(x.State==MEM_COMMIT&&rd&&!(x.Protect&PAGE_GUARD)){SIZE_T z=x.RegionSize;BYTE *b=(BYTE*)HeapAlloc(GetProcessHeap(),0,z);if(b){SIZE_T got;if(ReadProcessMemory(p,x.BaseAddress,b,z,&got)){for(SIZE_T i=0;i+4<=got;i+=4){uint32_t v;memcpy(&v,b+i,4);if(v==(uint32_t)target){wprintf(L"ptr=0x%08lX target=0x%08lX protect=0x%lX\n",(unsigned long)((uintptr_t)x.BaseAddress+i),(unsigned long)target,(unsigned long)x.Protect);if(++n>=200)break;}}}HeapFree(GetProcessHeap(),0,b);}}if(n>=200)break;a=(unsigned char*)x.BaseAddress+x.RegionSize;}wprintf(L"matches=%u pid=%lu target=0x%08lX\n",n,pid,(unsigned long)target);CloseHandle(p);return 0;}
