#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "ra2_product_manifest.h"

static const wchar_t kStopEvent[] = L"Local\\RA2ProductSuperStop";
typedef struct { DWORD object; BYTE b48,b56,b57,b58; DWORD d2C,d30,d34; BOOL valid; } SuperSnapshot;
static volatile BOOL g_stop=FALSE;
static BOOL WINAPI handler(DWORD t){if(t==CTRL_C_EVENT||t==CTRL_BREAK_EVENT||t==CTRL_CLOSE_EVENT){g_stop=TRUE;return TRUE;}return FALSE;}
static DWORD find_pid(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e={sizeof(e)};DWORD id=0;if(s==INVALID_HANDLE_VALUE)return 0;if(Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(p&&QueryFullProcessImageNameW(p,0,q,&n)&&!_wcsicmp(q,RA2_PRODUCT_GAME_PATH))id=e.th32ProcessID;if(p)CloseHandle(p);}}while(!id&&Process32NextW(s,&e));CloseHandle(s);return id;}
static BOOL r(HANDLE p,DWORD a,void*b,DWORD n){SIZE_T g=0;return ReadProcessMemory(p,(void*)(uintptr_t)a,b,n,&g)&&g==n;}
static BOOL w(HANDLE p,DWORD a,const void*b,DWORD n){SIZE_T g=0;return WriteProcessMemory(p,(void*)(uintptr_t)a,b,n,&g)&&g==n;}
static BOOL object_ok(HANDLE p,DWORD obj){MEMORY_BASIC_INFORMATION m;if(!obj||(obj&3u)||!VirtualQueryEx(p,(void*)(uintptr_t)obj,&m,sizeof(m))||m.State!=MEM_COMMIT)return FALSE;if(m.Protect&(PAGE_NOACCESS|PAGE_GUARD))return FALSE;return TRUE;}
static void restore_current(HANDLE p,DWORD root,DWORD savedRoot,SuperSnapshot*s){DWORD curRoot=0,arr=0,now=0;if(!savedRoot||!r(p,RA2_PRODUCT_PLAYER_ROOT,&curRoot,4)||curRoot!=savedRoot||!r(p,root+RA2_PRODUCT_SUPER_ARRAY_OFFSET,&arr,4)||!r(p,0x00A40D2C,&now,4))return;for(int i=0;i<8;i++)if(s[i].valid){DWORD obj=0;if(!r(p,arr+i*4,&obj,4)||obj!=s[i].object)continue;BYTE b;DWORD d;if(r(p,obj+0x48,&b,1)&&b==0)w(p,obj+0x48,&s[i].b48,1);if(r(p,obj+0x56,&b,1))w(p,obj+0x56,&s[i].b56,1);if(r(p,obj+0x57,&b,1)&&b==1)w(p,obj+0x57,&s[i].b57,1);if(r(p,obj+0x58,&b,1)&&b==0)w(p,obj+0x58,&s[i].b58,1);if(r(p,obj+0x2C,&d,4)&&d==now)w(p,obj+0x2C,&s[i].d2C,4);if(r(p,obj+0x30,&d,4)&&d==0)w(p,obj+0x30,&s[i].d30,4);if(r(p,obj+0x34,&d,4)&&d==0)w(p,obj+0x34,&s[i].d34,4);}}
int wmain(int argc,wchar_t**argv){if(argc!=1){wprintf(L"Usage: ra2_product_super_service.exe\n");return 2;}SetConsoleCtrlHandler(handler,TRUE);HANDLE stop=CreateEventW(NULL,TRUE,FALSE,kStopEvent);if(!stop)return 3;SuperSnapshot saved[8]={{0}};DWORD pid=0,savedRoot=0;HANDLE p=NULL;int missing=0;wprintf(L"SUPER_SERVICE running\n");while(!g_stop&&WaitForSingleObject(stop,100)==WAIT_TIMEOUT){DWORD nowPid=find_pid();if(!nowPid){if(++missing>=10)break;continue;}missing=0;if(nowPid!=pid){if(p)CloseHandle(p);p=NULL;pid=nowPid;savedRoot=0;memset(saved,0,sizeof(saved));}if(!p)p=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|PROCESS_VM_OPERATION|PROCESS_VM_WRITE,FALSE,pid);if(!p)continue;DWORD root=0,arr=0,now=0;if(!r(p,RA2_PRODUCT_PLAYER_ROOT,&root,4)||!root||!r(p,root+RA2_PRODUCT_SUPER_ARRAY_OFFSET,&arr,4)||!arr||!r(p,0x00A40D2C,&now,4))continue;if(root!=savedRoot){savedRoot=root;memset(saved,0,sizeof(saved));}for(int i=0;i<8;i++){DWORD obj=0;if(!r(p,arr+i*4,&obj,4)||!object_ok(p,obj))continue;SuperSnapshot*x=&saved[i];if(!x->valid||x->object!=obj){memset(x,0,sizeof(*x));x->object=obj;if(!r(p,obj+0x48,&x->b48,1)||!r(p,obj+0x56,&x->b56,1)||!r(p,obj+0x57,&x->b57,1)||!r(p,obj+0x58,&x->b58,1)||!r(p,obj+0x2C,&x->d2C,4)||!r(p,obj+0x30,&x->d30,4)||!r(p,obj+0x34,&x->d34,4)){memset(x,0,sizeof(*x));continue;}x->valid=TRUE;}BYTE z=0,one=1;DWORD zero=0;w(p,obj+0x48,&z,1);w(p,obj+0x58,&z,1);w(p,obj+0x57,&one,1);w(p,obj+0x2C,&now,4);w(p,obj+0x30,&zero,4);w(p,obj+0x34,&zero,4);}}if(p)restore_current(p,savedRoot,savedRoot,saved);if(p)CloseHandle(p);CloseHandle(stop);wprintf(L"SUPER_SERVICE stopped\n");return 0;}
