#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <bcrypt.h>
#include <stdio.h>
#include <wchar.h>
#include <string.h>
#include "ra2_product_manifest.h"

#pragma comment(lib, "bcrypt.lib")
static DWORD find_pid(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e={sizeof(e)};DWORD id=0;if(s==INVALID_HANDLE_VALUE)return 0;if(Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(p&&QueryFullProcessImageNameW(p,0,q,&n)&&!_wcsicmp(q,RA2_PRODUCT_GAME_PATH))id=e.th32ProcessID;if(p)CloseHandle(p);}}while(!id&&Process32NextW(s,&e));CloseHandle(s);return id;}
static BOOL hash_file(wchar_t*out){HANDLE f=CreateFileW(RA2_PRODUCT_GAME_PATH,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,OPEN_EXISTING,0,NULL);BCRYPT_ALG_HANDLE a=NULL;BCRYPT_HASH_HANDLE h=NULL;PUCHAR obj=NULL,dig=NULL;DWORD ol=0,dl=0,cb=0;BYTE buf[8192];ULONG got;BOOL ok=FALSE;if(f==INVALID_HANDLE_VALUE||BCryptOpenAlgorithmProvider(&a,BCRYPT_SHA256_ALGORITHM,NULL,0)<0)goto done;if(BCryptGetProperty(a,BCRYPT_OBJECT_LENGTH,(PUCHAR)&ol,4,&cb,0)<0||BCryptGetProperty(a,BCRYPT_HASH_LENGTH,(PUCHAR)&dl,4,&cb,0)<0)goto done;obj=HeapAlloc(GetProcessHeap(),0,ol);dig=HeapAlloc(GetProcessHeap(),0,dl);if(!obj||!dig||BCryptCreateHash(a,&h,obj,ol,NULL,0,0)<0)goto done;for(;;){if(!ReadFile(f,buf,sizeof(buf),&got,NULL))goto done;if(!got)break;if(BCryptHashData(h,buf,got,0)<0)goto done;}if(BCryptFinishHash(h,dig,dl,0)<0)goto done;for(DWORD i=0;i<dl;i++)swprintf_s(out+i*2,65-i*2,L"%02X",dig[i]);out[64]=0;ok=TRUE;done:if(h)BCryptDestroyHash(h);if(a)BCryptCloseAlgorithmProvider(a,0);if(obj)HeapFree(GetProcessHeap(),0,obj);if(dig)HeapFree(GetProcessHeap(),0,dig);if(f!=INVALID_HANDLE_VALUE)CloseHandle(f);return ok;}
static void put32(BYTE*p,DWORD v){memcpy(p,&v,4);}
static BOOL invoke(HANDLE p,DWORD target){BYTE stub[16];DWORD k=0;stub[k++]=0xB9;put32(stub+k,0x008324E0);k+=4;stub[k++]=0xE8;LPVOID mem=VirtualAllocEx(p,NULL,0x1000,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE);if(!mem)return FALSE;put32(stub+k,target-((DWORD)(uintptr_t)mem+k+4));k+=4;stub[k++]=0xC3;SIZE_T n=0;BOOL ok=WriteProcessMemory(p,mem,stub,k,&n)&&n==k;HANDLE t=ok?CreateRemoteThread(p,NULL,0,(LPTHREAD_START_ROUTINE)mem,NULL,0,NULL):NULL;if(t){ok=WaitForSingleObject(t,1000)==WAIT_OBJECT_0;CloseHandle(t);}VirtualFreeEx(p,mem,0,MEM_RELEASE);return ok;}
int wmain(int argc,wchar_t**argv){BOOL status=argc==1||!_wcsicmp(argv[1],L"--status"),on=argc==2&&!_wcsicmp(argv[1],L"--on"),off=argc==2&&!_wcsicmp(argv[1],L"--off");if(argc>2||(!status&&!on&&!off)){wprintf(L"Usage: ra2_product_fog.exe [--status|--on|--off]\n");return 2;}DWORD pid=find_pid();wchar_t sha[65];if(!pid||!hash_file(sha)){wprintf(L"TARGET_UNAVAILABLE\n");return 3;}if(_wcsicmp(sha,RA2_PRODUCT_SHA256)){wprintf(L"VERSION_MISMATCH\nWRITES=REFUSED\n");return 4;}if(status){wprintf(L"FOG=READY PID=%lu VERSION=MATCHED WRITES=NONE\n",pid);return 0;}HANDLE p=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_OPERATION|PROCESS_VM_WRITE|PROCESS_CREATE_THREAD,FALSE,pid);if(!p)return 5;BOOL ok=invoke(p,on?0x0055A120:0x0055A070);CloseHandle(p);wprintf(L"FOG=%ls\n",ok?(on?L"ON":L"OFF_RECOMPUTED"):L"FAILED");return ok?0:6;}
