#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <bcrypt.h>
#include <stdio.h>
#include <wchar.h>
#include <string.h>
#pragma comment(lib,"bcrypt.lib")
static const wchar_t path[]=L"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Command & Conquer Red Alert II\\game.exe";
static const wchar_t sha_expected[]=L"73288C03B58D370BE268CA6D156B4E33BFDB2066DC980359467D8852FF3B00DF";
static const DWORD offs[]={0x52B8,0x52BC,0x52C0,0x52C4,0x52C8};
static DWORD findpid(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e={0};DWORD r=0;e.dwSize=sizeof(e);if(s!=INVALID_HANDLE_VALUE&&Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE h=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(h&&QueryFullProcessImageNameW(h,0,q,&n)&&!_wcsicmp(q,path))r=e.th32ProcessID;if(h)CloseHandle(h);}}while(!r&&Process32NextW(s,&e));if(s!=INVALID_HANDLE_VALUE)CloseHandle(s);return r;}
static BOOL hashfile(wchar_t*out,DWORD cap){HANDLE f=CreateFileW(path,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,0,OPEN_EXISTING,0,0);BCRYPT_ALG_HANDLE a=0;BCRYPT_HASH_HANDLE h=0;PUCHAR obj=0,dig=0;DWORD ol=0,dl=0,cb=0;BYTE b[8192];ULONG n;BOOL ok=0;if(f==INVALID_HANDLE_VALUE||BCryptOpenAlgorithmProvider(&a,BCRYPT_SHA256_ALGORITHM,0,0)<0)goto done;if(BCryptGetProperty(a,BCRYPT_OBJECT_LENGTH,(PUCHAR)&ol,4,&cb,0)<0||BCryptGetProperty(a,BCRYPT_HASH_LENGTH,(PUCHAR)&dl,4,&cb,0)<0)goto done;obj=HeapAlloc(GetProcessHeap(),0,ol);dig=HeapAlloc(GetProcessHeap(),0,dl);if(!obj||!dig||BCryptCreateHash(a,&h,obj,ol,0,0,0)<0)goto done;for(;;){if(!ReadFile(f,b,sizeof(b),&n,0))goto done;if(!n)break;if(BCryptHashData(h,b,n,0)<0)goto done;}if(BCryptFinishHash(h,dig,dl,0)<0)goto done;for(DWORD i=0;i<dl;i++)swprintf_s(out+i*2,cap-i*2,L"%02X",dig[i]);out[64]=0;ok=1;done:if(h)BCryptDestroyHash(h);if(a)BCryptCloseAlgorithmProvider(a,0);if(obj)HeapFree(GetProcessHeap(),0,obj);if(dig)HeapFree(GetProcessHeap(),0,dig);if(f!=INVALID_HANDLE_VALUE)CloseHandle(f);return ok;}
int wmain(int argc,wchar_t**argv){BOOL apply=argc==2&&!_wcsicmp(argv[1],L"--apply"),restore=argc==2&&!_wcsicmp(argv[1],L"--restore");if(argc>1&&!apply&&!restore){wprintf(L"Usage: ra2_build_manager.exe [--apply|--restore]\n");return 2;}DWORD id=findpid();wchar_t sha[65];if(!id||!hashfile(sha,65)){wprintf(L"Target or hash unavailable.\n");return 3;}wprintf(L"pid=%lu sha256=%ls\n",id,sha);if(_wcsicmp(sha,sha_expected)){wprintf(L"VERSION_MISMATCH: refusing memory writes.\n");return 4;}HANDLE p=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|((apply||restore)?(PROCESS_VM_OPERATION|PROCESS_VM_WRITE):0),0,id);if(!p)return 5;DWORD root=0;SIZE_T n=0;if(!ReadProcessMemory(p,(void*)0x00A35DB4,&root,4,&n)||n!=4||!root){CloseHandle(p);return 6;}wprintf(L"object=0x%08lX\n",root);DWORD cur[5];for(int i=0;i<5;i++){if(!ReadProcessMemory(p,(void*)(uintptr_t)(root+offs[i]),&cur[i],4,&n)||n!=4){CloseHandle(p);return 7;}wprintf(L"+0x%lX=%lu\n",(unsigned long)offs[i],(unsigned long)cur[i]);}if(apply||restore){for(int i=0;i<5;i++){DWORD expected=apply?cur[i]:15;if(restore&&cur[i]!=15){wprintf(L"PATCH_REFUSED: field +0x%lX is not 15.\n",(unsigned long)offs[i]);CloseHandle(p);return 8;}DWORD v=apply?15:((offs[i]==0x52BC)?3:((offs[i]==0x52C4)?2:0));SIZE_T w=0;if(!WriteProcessMemory(p,(void*)(uintptr_t)(root+offs[i]),&v,4,&w)||w!=4){CloseHandle(p);return 9;}}wprintf(L"PATCH_STATE=%ls\n",apply?L"APPLIED":L"UNAPPLIED");}else wprintf(L"PATCH_STATE=READ_ONLY\nNo memory was written.\n");CloseHandle(p);return 0;}
