#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static const wchar_t path[]=L"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Command & Conquer Red Alert II\\game.exe";
static DWORD pid(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e={0};DWORD r=0;e.dwSize=sizeof(e);if(s!=INVALID_HANDLE_VALUE&&Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE h=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(h&&QueryFullProcessImageNameW(h,0,q,&n)&&!_wcsicmp(q,path))r=e.th32ProcessID;if(h)CloseHandle(h);}}while(!r&&Process32NextW(s,&e));if(s!=INVALID_HANDLE_VALUE)CloseHandle(s);return r;}
static void put(BYTE*p,DWORD v){memcpy(p,&v,4);}
int wmain(void){DWORD id=pid();if(!id)return 2;HANDLE p=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|PROCESS_VM_OPERATION|PROCESS_VM_WRITE|PROCESS_CREATE_THREAD,FALSE,id);if(!p)return 3;DWORD root=0,arr=0,obj=0;SIZE_T n=0;if(!ReadProcessMemory(p,(void*)0x00A35DB4,&root,4,&n)||n!=4||!root||!ReadProcessMemory(p,(void*)(uintptr_t)(root+0x1A0),&arr,4,&n)||n!=4||!arr){CloseHandle(p);return 4;}int done=0;for(DWORD i=2;i<=2;i++){if(!ReadProcessMemory(p,(void*)(uintptr_t)(arr+i*4),&obj,4,&n)||n!=4||obj<0x10000)continue;BYTE zero48=0;SIZE_T w48=0;if(!WriteProcessMemory(p,(void*)(uintptr_t)(obj+0x48),&zero48,1,&w48)||w48!=1)continue;BYTE stub[80];DWORD k=0;stub[k++]=0x60;stub[k++]=0xB8;put(stub+k,i);k+=4;stub[k++]=0x50;stub[k++]=0xBA;put(stub+k,0x00A35DB4);k+=4;stub[k++]=0x8B;stub[k++]=0x12;stub[k++]=0x8B;stub[k++]=0x8A;put(stub+k,0x1A0);k+=4;stub[k++]=0x8B;stub[k++]=0x0C;stub[k++]=0x81;stub[k++]=0xE8;LPVOID mem=VirtualAllocEx(p,NULL,0x1000,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE);if(!mem)continue;put(stub+k,(DWORD)(0x0069D690-((DWORD)(uintptr_t)mem+k+4)));k+=4;stub[k++]=0x61;stub[k++]=0xC3;if(!WriteProcessMemory(p,mem,stub,k,&n)||n!=k){VirtualFreeEx(p,mem,0,MEM_RELEASE);continue;}HANDLE t=CreateRemoteThread(p,NULL,0,(LPTHREAD_START_ROUTINE)mem,NULL,0,NULL);if(t){DWORD wr=WaitForSingleObject(t,1000);if(wr==WAIT_OBJECT_0)done++;CloseHandle(t);}VirtualFreeEx(p,mem,0,MEM_RELEASE);}wprintf(L"SUPER_RESET_CALL completed=%d\n",done);CloseHandle(p);return done?0:5;}
