#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static const wchar_t path[]=L"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Command & Conquer Red Alert II\\game.exe";
static const uintptr_t patch_addr=0x00775F24;
static const BYTE original[5]={0x2B,0xD7,0x89,0x56,0x24};
static DWORD findpid(void){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e={0};DWORD r=0;e.dwSize=sizeof(e);if(s!=INVALID_HANDLE_VALUE&&Process32FirstW(s,&e))do{if(!_wcsicmp(e.szExeFile,L"game.exe")){HANDLE h=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,e.th32ProcessID);wchar_t q[MAX_PATH];DWORD n=MAX_PATH;if(h&&QueryFullProcessImageNameW(h,0,q,&n)&&!_wcsicmp(q,path))r=e.th32ProcessID;if(h)CloseHandle(h);}}while(!r&&Process32NextW(s,&e));if(s!=INVALID_HANDLE_VALUE)CloseHandle(s);return r;}
static void put32(BYTE*p,DWORD v){memcpy(p,&v,4);}
int wmain(int argc,wchar_t**argv){BOOL apply=argc==2&&!_wcsicmp(argv[1],L"--apply"),restore=argc==2&&!_wcsicmp(argv[1],L"--restore");if(argc>1&&!apply&&!restore){wprintf(L"Usage: ra2_guarded_instant.exe [--apply|--restore]\n");return 2;}DWORD id=findpid();if(!id){wprintf(L"未找到目标 game.exe。\n");return 3;}DWORD access=PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|((apply||restore)?(PROCESS_VM_OPERATION|PROCESS_VM_WRITE):0);HANDLE p=OpenProcess(access,FALSE,id);if(!p)return 4;BYTE cur[5];SIZE_T n=0;if(!ReadProcessMemory(p,(void*)patch_addr,cur,5,&n)||n!=5){CloseHandle(p);return 5;}wprintf(L"module+0x375F24: %02X %02X %02X %02X %02X\n",cur[0],cur[1],cur[2],cur[3],cur[4]);if(restore){if(memcmp(cur,original,5)==0){wprintf(L"PATCH_STATE=UNAPPLIED\n");CloseHandle(p);return 0;}if(cur[0]!=0xE9){wprintf(L"PATCH_REFUSED: bytes are not guarded patch or original.\n");CloseHandle(p);return 6;}SIZE_T w=0;if(!WriteProcessMemory(p,(void*)patch_addr,original,5,&w)||w!=5||!FlushInstructionCache(p,(void*)patch_addr,5)){CloseHandle(p);return 7;}wprintf(L"PATCH_STATE=UNAPPLIED\n");CloseHandle(p);return 0;}
    if(!apply){wprintf(L"PATCH_STATE=%ls\nNo memory was written.\n",cur[0]==0xE9?L"APPLIED":L"UNAPPLIED");CloseHandle(p);return 0;}
    if(memcmp(cur,original,5)!=0){wprintf(L"PATCH_REFUSED: unexpected original bytes.\n");CloseHandle(p);return 7;}
    BYTE stub[128];SIZE_T k=0;stub[k++]=0x50;stub[k++]=0xA1;put32(stub+k,0x00A35DB4);k+=4;const DWORD offs[]={0x52D8,0x52DC,0x52E0,0x52E4,0x52E8,0x52F8};DWORD je[6];for(int i=0;i<6;i++){stub[k++]=0x39;stub[k++]=0xB0;put32(stub+k,offs[i]);k+=4;stub[k++]=0x74;je[i]=(DWORD)k;k++;}stub[k++]=0x2B;stub[k++]=0xD7;stub[k++]=0x58;DWORD back=(DWORD)(patch_addr+5);stub[k++]=0xE9;put32(stub+k,back);k+=4;DWORD set=(DWORD)k;stub[k++]=0xBA;put32(stub+k,53);k+=4;stub[k++]=0x58;stub[k++]=0xE9;put32(stub+k,back);k+=4;for(int i=0;i<6;i++){int8_t rel=(int8_t)(set-(je[i]+1));stub[je[i]]= (BYTE)rel;}LPVOID cave=VirtualAllocEx(p,NULL,0x1000,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE);if(!cave){CloseHandle(p);return 8;}DWORD cave32=(DWORD)(uintptr_t)cave;SIZE_T w=0;if(!WriteProcessMemory(p,cave,stub,k,&w)||w!=k){VirtualFreeEx(p,cave,0,MEM_RELEASE);CloseHandle(p);return 9;}BYTE jump[5]={0xE9,0,0,0,0};put32(jump+1,cave32-(DWORD)(patch_addr+5));if(!WriteProcessMemory(p,(void*)patch_addr,jump,5,&w)||w!=5||!FlushInstructionCache(p,(void*)patch_addr,5)){VirtualFreeEx(p,cave,0,MEM_RELEASE);CloseHandle(p);return 10;}wprintf(L"guarded trampoline=0x%08lX\nPATCH_STATE=APPLIED\n",(unsigned long)cave32);CloseHandle(p);return 0;}
